# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab56dd0dcfe079243cb525cd3621e05f5aa9efaf46215110426fc84a259b211f8be5df9299f151bc83a7c85954ccb879196741b93cbceaebfe00f9d8b2735cb

test:
  secret_key_base: ec89ffd40b7a22542d9da2fdec6c30cf13c13a7fea53c387ddb11f1cb6b744d3afa5f87a3d0ffc49a0ab63f700e02b6bc5885df288be5e3d0fa8f82747b85f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
